---
- name: Check if CFEngine is installed
  stat:
    path: /var/cfengine/bin/cf-agent
  register: cfengin3_stat

- name: Check CFEngine version
  shell: "set -o pipefail && /var/cfengine/bin/cf-agent --version | sed -e 's/^[^0-9]\\+//g' | head -n1"
  args:
    executable: /bin/bash
  register: cfengine_version
  when: cfengin3_stat.stat.exists

- name: Install cf-remote python package
  ansible.builtin.pip:
    name: cf-remote
  delegate_to: localhost

- name: Install CFEngine on the target host
  ansible.builtin.command:
    cmd: >
      cf-remote --version "{{ version }}" install --edition "{{ edition }}"
        {{ '--clients' if package == 'client' else '--hub' }} "{{ ansible_user }}@{{ ansible_host }}:{{ ansible_port | default }}"
        {{ '--bootstrap ' + bootstrap if bootstrap else "" }}
        {{ '--trust-keys ' + trust_keys if trust_keys else "" }}
        --remote-download
  environment:
    CF_REMOTE_SSH_KEY: "{{ ansible_ssh_private_key_file }}"
  when: (not cfengin3_stat.stat.exists or cfengine_version.stdout != version) and bootstrap | length > 0
  delegate_to: localhost
