---
- name: cfengine | Check if CFEngine is installed
  stat:
    path: /var/cfengine/bin/cf-agent
  register: cfengin3_stat

- name: cfengine | Check CFEngine version
  shell: "/var/cfengine/bin/cf-agent --version  | sed -e 's/^[^0-9]\\+//g' | head -n1"
  register: cfengine_version
  when: cfengin3_stat.stat.exists

- name: cfengine | Install cf-remote python package
  ansible.builtin.pip:
    name: cf-remote
  delegate_to: localhost

- name: cfengine | Transfer the trust key to the host
  ansible.builtin.copy:
    src: "{{ trust_key }}"
    dest: /tmp/trust_key.pem
    owner: root
    group: root
    mode: "000"
  when: trust_key != ""

- name: cfengine | Install CFEngine on the target host
  ansible.builtin.command:
    cmd: >
      cf-remote --version "{{ version }}" install --edition "{{ edition }}"
        {{ '--clients' if package == 'client' else '--hub' }} "{{ ansible_user }}@{{ ansible_host }}:{{ ansible_port | default}}"
        {{ '--bootstrap ' + bootstrap if bootstrap else "" }}
        {{ '--trust-keys /tmp/trust_key.pem' if trust_key else "" }}
        --remote-download
  environment:
    CF_REMOTE_SSH_KEY: "{{ ansible_ssh_private_key_file }}"
  when: (not cfengin3_stat.stat.exists or cfengine_version.stdout != version) and bootstrap != ""
  delegate_to: localhost

- name: cfengine | Remove the trust key from the host
  ansible.builtin.file:
    path: "/tmp/trust_key.pem"
    state: absent
  when: trust_key != ""
